megano/cart/urls.py
from django.urls import path

from .views import (
    AddProductToCartView,
    AddProductView,
    TakeProductView,
    CartListView,
    DeleteProductFromCartView,
    ClearCartView
)

app_name = 'cart'

urlpatterns = [
    path('', CartListView.as_view(), name='index'),
    path('<int:offer_id>/', AddProductToCartView.as_view(), name='add_product_to_cart'),
    path('add_product/<slug:slug>/', AddProductView.as_view(), name='add_product'),
    path('take_product/<slug:slug>/', TakeProductView.as_view(), name='take_product'),
    path('delete_product/<slug:slug>/', DeleteProductFromCartView.as_view(), name='delete_product'),
    path('cart/clear/', ClearCartView.as_view(), name='cart_clear'),
]

megano/compare/urls.py
from django.urls import path

from compare.views import (AddToComparisonView,
                           ComparisonView,
                           ComparisonErrorView,
                           ComparisonNoneView,
                           ClearComparisonView,
                           )

app_name = 'compare'

urlpatterns = [
    path('add-to-comparison/<int:product_id>/', AddToComparisonView.as_view(), name='add_to_comparison'),
    path('clear_comparison/', ClearComparisonView.as_view(), name='clear_comparison'),
    path('comparison/', ComparisonView.as_view(), name='comparison'),
    path('comparison-error/', ComparisonErrorView.as_view(), name='comparison_error'),
    path('comparison-none/', ComparisonNoneView.as_view(), name='comparison_none'),
]

megano/megano/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls.i18n import i18n_patterns
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('i18n/', include('django.conf.urls.i18n')),
]

urlpatterns += i18n_patterns(
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('cart/', include('cart.urls')),
    path('', include('store.urls')),
    path('', include('compare.urls')),
    path('auth/', include('authorization.urls')),
)
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

megano/store/urls.py
from django.urls import path

from .views import (CatalogListView,
                    ProductDetailView,
                    SettingsView,
                    ClearCacheAll,
                    ClearCacheBanner,
                    ClearCacheCart,
                    ClearCacheProductDetail,
                    ClearCacheSeller,
                    ClearCacheCatalog,
                    SiteName,
                    CacheSetupBannerView,
                    CacheSetupCartView,
                    CacheSetupSellerView,
                    CacheSetupCatalogView,
                    CacheSetupProdDetailView,
                    MainPage,
                    OrderView,
                    OrderRegisterView,
                    OrderConfirmView,
                    DiscountList,
                    DiscountDetail,
                    PaymentFormView,
                    PaymentProgressView,
                    )

app_name = 'store'

urlpatterns = [
    path('catalog/', CatalogListView.as_view(), name='catalog'),
    path('catalog/<slug:slug>/', CatalogListView.as_view(), name='category'),
    path('product/<slug:slug>/', ProductDetailView.as_view(), name='product-detail'),
    path('', MainPage.as_view(), name='index'),
    path('order/<int:pk>/payment/', PaymentFormView.as_view(), name='payment-form'),
    path('order/<int:pk>/payment/progress/', PaymentProgressView.as_view(), name='payment-progress'),
    path('order-reg/', OrderRegisterView.as_view(), name='order_reg'),
    path('order-create/<int:pk>/', OrderView.as_view(), name='order_create'),
    path('order-confirm/<int:pk>/', OrderConfirmView.as_view(), name='order_confirm'),
    path('settings/', SettingsView.as_view(), name='settings'),
    path('clear-all/', ClearCacheAll.as_view(), name='clear_all_cache'),
    path('clear-banner/', ClearCacheBanner.as_view(), name='clear_banner_cache'),
    path('clear-cart/', ClearCacheCart.as_view(), name='clear_cart_cache'),
    path('clear-seller/', ClearCacheSeller.as_view(), name='clear_seller'),
    path('clear-catalog/', ClearCacheCatalog.as_view(), name='clear_catalog'),
    path('clear-product-detail/', ClearCacheProductDetail.as_view(), name='clear_product_detail'),
    path('site-name/', SiteName.as_view(), name='site_name'),
    path('cache-time-banner/', CacheSetupBannerView.as_view(), name='cache_time_banner'),
    path('cache-time-cart/', CacheSetupCartView.as_view(), name='cache_time_cart'),
    path('cache-time-prod-detail/', CacheSetupProdDetailView.as_view(), name='cache_time_prod_detail'),
    path('cache-time-seller/', CacheSetupSellerView.as_view(), name='cache_time_seller'),
    path('cache-time-catalog/', CacheSetupCatalogView.as_view(), name='cache_time_catalog'),
    path('discounts/', DiscountList.as_view(), name='discounts'),
    path('discounts/<slug:slug>/', DiscountDetail.as_view(), name='discount_details'),
]

megano/cart/models.py
from django.db import models
from django.urls import reverse
from django.utils.translation import gettext_lazy as _

from store.models import Product, Orders


class Cart(models.Model):
    """
    Описание модели Корзины

    Orders  - :model:`store.Orders`\n
    Product - :model:`store.Product`
    """

    ordering = _('Заказ')

    order = models.ForeignKey(Orders, on_delete=models.CASCADE, verbose_name=_('Заказ'))
    products = models.ForeignKey(Product, on_delete=models.CASCADE, verbose_name=_('Продукты'))
    quantity = models.IntegerField(default=1, verbose_name=_('Количество'))
    created_at = models.DateTimeField(auto_now_add=True, verbose_name=_('Дата создания'), db_index=True)
    updated_at = models.DateTimeField(auto_now=True, verbose_name=_('Дата изменения'))

    def __str__(self) -> str:
        """
        Возвращает имя пользователя и название продукта в виде:
        username: product_name
        """

        return f'({self.ordering} №_{self.order.id}'

    def get_absolute_url(self) -> str:
        """
        Возвращает путь на детальную страницу товаров корзины.
        """

        return reverse('detail', kwargs={'id': self.id})

    class Meta:
        db_table = 'carts'
        ordering = ['-created_at']
        verbose_name = _('корзину')
        verbose_name_plural = _('корзины')

megano/store/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django.utils.translation import gettext_lazy as _
from multiupload.fields import MultiFileField

from authorization.models import Profile
from .models import Orders, Product


class ReviewsForm(forms.Form):
    review = forms.CharField(widget=forms.Textarea, max_length=100)


class OrderCreateForm(forms.ModelForm):
    """
    Класс формы для оформления Заказа.
    """

    name_placeholder = _("Иванов Иван Иванович")

    name = forms.CharField(
        max_length=100,
        label='ФИО',
        widget=forms.TextInput(attrs={
            'class': "form-input",
            'id': "name",
            'name': "name",
            'type': "text",
            'placeholder': name_placeholder,
        }),
    )
    phone = forms.CharField(
        max_length=20,
        label='Телефон',
        widget=forms.TextInput(attrs={
            'class': "form-input",
            'id': "phone",
            'name': "phone",
            'type': "text",
            'placeholder': "+79991230000",
            'data-mask': "+7(999)9999999",
        }),
    )
    delivery = forms.ChoiceField(
        choices=Orders.Delivery.choices[1:],
        widget=forms.RadioSelect(attrs={
            'class': "toggle-box",
            'id': "delivery",
            'name': "delivery",
            'type': "radio",
            'checked': "checked"
        }),
    )
    payment = forms.ChoiceField(
        choices=Orders.Payment.choices[1:],
        widget=forms.RadioSelect(attrs={
            'class': "toggle-box",
            'id': "payment",
            'name': "payment",
            'type': "radio",
        }),
    )
    city = forms.CharField(max_length=100, label='Город', help_text=_('Город проживания'))
    address = forms.CharField(max_length=200, label='Адрес', help_text=_('Адрес доставки'))
    email = forms.EmailField(max_length=80, label='Почта', help_text=_('Почта'))

    def clean_phone(self):
        """"
        Функция для очистки номера проверки его на уникальность и приведения к int
        """
        phone_str = self.cleaned_data['phone']
        chars_to_remove = ['(', ')']
        for char in chars_to_remove:
            phone_str = phone_str.replace(char, '')
        phone = phone_str[2:]
        return phone

    class Meta:
        model = Profile
        fields = [
            'name', 'phone', 'city', 'address',
            'delivery', 'payment',
        ]


class RegisterForm(UserCreationForm):
    """
    Класс формы для регистрации пользователя
    """

    username = forms.CharField(label='Логин', widget=forms.TextInput(attrs={'class': 'form-input'}))
    password1 = forms.CharField(label='Пароль', widget=forms.PasswordInput(attrs={'class': 'form-input'}))
    password2 = forms.CharField(label='Повтор пароля', widget=forms.PasswordInput(attrs={'class': 'form-input'}))
    phone = forms.CharField(
        max_length=20,
        label='Телефон',
        widget=forms.TextInput(attrs={
            'class': "form-input",
            'id': "phone",
            'name': "phone",
            'type': "text",
            'placeholder': "+79991230000",
        }),
    )

    def clean_phone(self):
        phone = self.cleaned_data['phone']
        if Profile.objects.filter(phone=phone).exists():
            raise forms.ValidationError(_("Такой телефон уже существует"))

    def clean_username(self):
        username = self.cleaned_data['username']
        if User.objects.filter(username=username).exists():
            raise forms.ValidationError(_("Такой логин уже существует"))

        return username

    def clean_email(self):
        email = self.cleaned_data['email']
        if User.objects.filter(email=email).exists():
            raise forms.ValidationError(_("Данный email уже существует."))

    def clean_password2(self):
        passw1 = self.cleaned_data['password1']
        passw2 = self.cleaned_data['password2']
        if passw1 != passw2:
            raise forms.ValidationError(_("Пароли не совпадают"))
        if len(passw1) < 6:
            raise forms.ValidationError(_("Пароль должен содержать не менее 6 символов"))

    class Meta:
        model = User
        fields = ('username', 'phone', 'email', 'password1', 'password2')


class SearchForm(forms.ModelForm):
    name = forms.CharField(
        max_length=120,
        widget=forms.TextInput(attrs={
            'class': 'search-input',
            'id': 'query',
            'name': 'query',
            'placeholder': 'NVIDIA GeForce RTX 3060',
        })
    )

    class Meta:
        model = Product
        fields = ['name',]


class PaymentForm(forms.Form):
    bill = forms.CharField(
        widget=forms.TextInput(attrs={
            'class': 'form-input Payment-bill',
            'id': 'numero1',
            'name': 'numero1',
            'type': 'text',
            'placeholder': '9999 9999',
            'data-mask': "9999 9999",
            'data-validate': "require pay",
        })
    )


class JSONImportForm(forms.Form):
    """
    Вьюшка импорта JSON файлов
    """

    json_file = MultiFileField(label=_('json_file'), min_num=1, max_num=10)
    email = forms.EmailField(label=_('email'))

megano/cart/views.py
from django.shortcuts import get_object_or_404, redirect
from django.http import HttpResponseRedirect
from django.views.generic import TemplateView

from services.services import DiscountProduct
from .cart import Cart
from store.models import Product, Offer

from typing import Any


class CartListView(TemplateView):
    template_name = 'store/cart.html'

    def get_context_data(self, **kwargs) -> dict[str, Any]:
        context = super().get_context_data(**kwargs)
        discount = DiscountProduct()
        context.update(
            {
                'carts': Cart(self.request),
                'offers': Offer.objects.all(),
                'total_price': discount.get_priority_discount(cart=Cart(self.request))
            }
        )
        return context

    def post(self, request) -> HttpResponseRedirect:
        offer = Offer.objects.get(id=request.POST.get('offer'))
        carts = Cart(request)
        for item in carts:
            if item['product'].id == offer.product.id:
                carts.update_date(offer, offer.unit_price)
        return HttpResponseRedirect(request.META.get('HTTP_REFERER'))


class AddProductToCartView(TemplateView):
    """
    Добавление товара в корзину
    """

    template_name = 'store/cart.html'

    def get(self, request, *args, **kwargs) -> HttpResponseRedirect:
        cart = Cart(request)
        offer = get_object_or_404(Offer, id=kwargs['offer_id'])
        cart.add_product(offer, update=False)
        return HttpResponseRedirect(request.META.get('HTTP_REFERER'))


class AddProductView(TemplateView):
    """
    Добавить одну единицу товара в корзине (+1шт.)
    """

    template_name = 'store/cart.html'

    def get(self, request, *args, **kwargs) -> HttpResponseRedirect:
        cart = Cart(request)
        product = get_object_or_404(Product, slug=kwargs['slug'])
        cart_add = int(cart.cart[f'{product.id}']['offer_id'])
        cart.add(get_object_or_404(Offer, id=cart_add))
        return HttpResponseRedirect(self.request.META.get('HTTP_REFERER'))


class TakeProductView(TemplateView):
    """
    Убрать одну единицу товара в корзине (-1шт.)
    """

    template_name = 'store/cart.html'

    def get(self, request, *args, **kwargs) -> HttpResponseRedirect:
        cart = Cart(request)
        product = get_object_or_404(Product, slug=kwargs['slug'])
        cart_take = int(cart.cart[f'{product.id}']['offer_id'])
        cart.take(get_object_or_404(Offer, id=cart_take))
        return HttpResponseRedirect(self.request.META.get('HTTP_REFERER'))


class DeleteProductFromCartView(TemplateView):
    """
    Удаление продукта из корзины
    """

    template_name = 'store/cart.html'

    def get(self, request, *args, **kwargs) -> HttpResponseRedirect:
        cart = Cart(request)
        cart.remove(get_object_or_404(Product, slug=kwargs['slug']))
        return HttpResponseRedirect(self.request.META.get('HTTP_REFERER'))


class ClearCartView(TemplateView):
    """
    Очистка корзины от всех продуктов
    """

    template_name = 'store/cart.html'

    def get(self, request, *args, **kwargs) -> HttpResponseRedirect:
        cart = Cart(request)
        cart.clear()
        return redirect('cart:index')

megano/templates/store/cart.html
{% include 'base/header.html' %}
{% load i18n static %}
{% load converter %}

{% block content %}
  <div class="Middle Middle_top">
    <div class="Section">
      <div class="wrap">
        {% if carts %}
          <form class="form Cart" action="#" method="post">
            {% csrf_token %}
            {% for item in carts %}
              {% with cart=item.product %}
                <div class="Cart-product">
                  <div class="Cart-block Cart-block_row">
                    <div class="Cart-block Cart-block_pict">
                      <a class="Cart-pict" href="#">
                        {% if cart.preview %}
                          <img class="Cart-img"
                               src="{{ cart.preview.url }}"
                               width="120px"
                               alt="{{ cart.name }}"/>
                        {% else %}
                          <img class="Cart-img"
                               src="{% static 'assets/img/content/home/placeholder.png' %}"
                               width="120px"
                               alt="empty_photo"/>
                        {% endif %}
                      </a>
                    </div>
                    <div class="Cart-block Cart-block_info">
                      <a class="Cart-title" href="#">{{ cart.name }}</a>
                      <div class="Cart-desc">{{ cart.description.text_bottom }}</div>
                    </div>
                    <div class="Cart-block Cart-block_price">
                      {% if item.d_price != 'None' %}
                        <div class="Cart-price Cart-price_old">{{ item.price }}$
                        </div>
                        <div class="Cart-price">{{ item.d_price }}$
                        </div>
                      {% else %}
                        <div class="Cart-price">{{ item.price }}$
                        </div>
                      {% endif %}
                    </div>
                  </div>
                  <div class="Cart-block Cart-block_row">
                    <div class="Cart-block Cart-block_seller">
                      <!-- - var options = setOptions(items, ['value', 'selected', 'disabled']);-->
                      <div>
                        <form method="post">
                          {% csrf_token %}
                          <select name="offer" id="element">
                            <option value="{{ item.offer_id }}">{{ item.offer_name }}</option>
                            {% for offer in cart.offers.all %}
                              <option value="{{ offer.id }}">{{ offer.seller.name_store }}</option>
                            {% endfor %}
                          </select>
                          <button style="width: 100%" type="submit">{% translate 'Показать' %}</button>
                        </form>
                      </div>
                    </div>
                    <div class="Cart-block Cart-block_amount">
                      {% for offer in offers %}
                        {% if offer.id  ==  item.offer_id|converter_to_int %}
                          <div class="Cart-amount">
                            <div class="Amount">
                              {% if offer.amount > 0 %}
                                <button class="button-visible take-product"
                                        type="button">
                                  <a href="{% url 'cart:take_product' cart.slug %}">—</a>
                                </button>
                                <label class="quantity-product">{{ item.quantity }}</label>
                                <button class="button-visible add-product"
                                        type="button">
                                  <a href="{% url 'cart:add_product' cart.slug %}">+</a>
                                </button>
                              {% else %}
                                <div>
                                  <span>{% translate 'Товара нет на складе' %}.</span>
                                  <span>{% translate 'Выберите продавца' %}.</span>
                                </div>
                              {% endif %}
                            </div>
                          </div>
                        {% endif %}
                      {% endfor %}

                    </div>
                    <div class="Cart-block Cart-block_delete">
                      <a class="Cart-delete" href="{% url 'cart:delete_product' cart.slug %}">
                        <img src="{% static 'assets/img/icons/card/delete.svg' %}"
                             alt="delete.svg"/>
                      </a>
                    </div>
                  </div>
                </div>
              {% endwith %}
            {% endfor %}
            <div class="Cart-total">
              <div class="Cart-block Cart-block_total">
                <strong class="Cart-title">{% translate 'Итого' %}:
                  {% if total_price != cart.get_total_price %}
                    </strong><span class="Cart-price">{{ total_price }}$</span>
                    <span class="Cart-price_old">{{ cart.get_total_price }}$</span>
                  {% else %}
                    </strong><span class="Cart-price">{{ total_price }}$</span>
                  {% endif %}
              </div>
              <div class="Cart-block">
                {% if user.is_authenticated %}
                  <a class="btn btn_success btn_lg"
                     href="{% url 'store:order_create' user.id %}">{% translate 'Оформить заказ' %}
                  </a>
                {% else %}
                  <a class="btn btn_success btn_lg"
                     href="{% url 'store:order_reg' %}">{% translate 'Оформить заказ' %}
                  </a>
                {% endif %}
              </div>
            </div>
          </form>
        {% else %}
          <div class="cart-empty">
            <h1 class="form-title">{% translate 'Корзина пуста' %}</h1>
            <img class="cart-empty-img" src="{% static 'assets/img/content/home/VBWY.gif' %}"
                 alt="cart_empty">
          </div>
        {% endif %}
      </div>
    </div>
  </div>
{% endblock %}

{% include 'base/footer.html' %}

megano/templates/store/paginator.html
{% load static %}

<div class="Pagination">
  <div class="Pagination-ins">
    {% if page_obj.has_previous %}
      <a class="Pagination-element Pagination-element_prev" href="?page={{ page_obj.previous_page_number }}"><img
              src="{% static 'assets/img/icons/prevPagination.svg' %}" alt="prevPagination.svg"/></a>
      <a class="Pagination-element" href="?page={{ page_obj.previous_page_number }}"><span
              class="Pagination-text">{{ page_obj.previous_page_number }}</span></a>
    {% endif %}

    <a class="Pagination-element Pagination-element_current" href="#"><span
            class="Pagination-text">{{ page_obj.number }}</span></a>

    {% if page_obj.has_next %}
      <a class="Pagination-element" href="?page={{ page_obj.next_page_number }}"><span
              class="Pagination-text">{{ page_obj.next_page_number }}</span></a>
      <a class="Pagination-element Pagination-element_prev" href="?page={{ page_obj.next_page_number }}"><img
              src="{% static 'assets/img/icons/nextPagination.svg' %}" alt="nextPagination.svg"/></a>
    {% endif %}
  </div>
</div>

megano/templates/store/products_changelist.html
{% extends 'admin/change_list.html' %}
{% load i18n %}

{% block object-tools-items %}
  {% load admin_urls %}
  <li>
    <a class="addlink" href="{% url 'admin:import_json_file' %}">
      {% translate 'Загрузить товары' %}
    </a>
  </li>
  {{ block.super }}
{% endblock %}