megano/authorization/urls.py
from django.urls import path

from .views import (
    ProfileDetailView,
    ProfileUpdateView,
    ProfileOrders,
    SellerDetail,
    RegisterView,
    UserLoginView,
    UserLogoutView,
    ProfileOrderPage,
    ProfileHistoryView,
)

app_name = 'profile'

urlpatterns = [
    path('personal_account/<slug:slug>/', ProfileDetailView.as_view(), name='profile_details'),
    path('personal_account/<slug:slug>/profile_date_form/', ProfileUpdateView.as_view(), name='profile'),
    path('personal_account/<slug:slug>/history_orders/', ProfileOrders.as_view(), name='history_orders'),
    path('personal_account/<slug:slug>/history_view/', ProfileHistoryView.as_view(), name='history_view'),
    path('seller/<slug:slug>/', SellerDetail.as_view(), name='seller'),
    path('register/', RegisterView.as_view(), name='register'),
    path('login/', UserLoginView.as_view(), name='login'),
    path('logout/', UserLogoutView.as_view(), name='logout'),
    path('personal_account/<slug:slug>/history_orders/detailed_order_page/<int:pk>/',
         ProfileOrderPage.as_view(), name='detailed_order'),
]

megano/cart/urls.py
from django.urls import path

from .views import (
    AddProductToCartView,
    AddProductView,
    TakeProductView,
    CartListView,
    DeleteProductFromCartView,
    ClearCartView
)

app_name = 'cart'

urlpatterns = [
    path('', CartListView.as_view(), name='index'),
    path('<int:offer_id>/', AddProductToCartView.as_view(), name='add_product_to_cart'),
    path('add_product/<slug:slug>/', AddProductView.as_view(), name='add_product'),
    path('take_product/<slug:slug>/', TakeProductView.as_view(), name='take_product'),
    path('delete_product/<slug:slug>/', DeleteProductFromCartView.as_view(), name='delete_product'),
    path('cart/clear/', ClearCartView.as_view(), name='cart_clear'),
]

megano/compare/urls.py
from django.urls import path

from compare.views import (AddToComparisonView,
                           ComparisonView,
                           ComparisonErrorView,
                           ComparisonNoneView,
                           ClearComparisonView,
                           )

app_name = 'compare'

urlpatterns = [
    path('add-to-comparison/<int:product_id>/', AddToComparisonView.as_view(), name='add_to_comparison'),
    path('clear_comparison/', ClearComparisonView.as_view(), name='clear_comparison'),
    path('comparison/', ComparisonView.as_view(), name='comparison'),
    path('comparison-error/', ComparisonErrorView.as_view(), name='comparison_error'),
    path('comparison-none/', ComparisonNoneView.as_view(), name='comparison_none'),
]

megano/megano/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls.i18n import i18n_patterns
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('i18n/', include('django.conf.urls.i18n')),
]

urlpatterns += i18n_patterns(
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('cart/', include('cart.urls')),
    path('', include('store.urls')),
    path('', include('compare.urls')),
    path('auth/', include('authorization.urls')),
)
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

megano/store/urls.py
from django.urls import path

from .views import (CatalogListView,
                    ProductDetailView,
                    SettingsView,
                    ClearCacheAll,
                    ClearCacheBanner,
                    ClearCacheCart,
                    ClearCacheProductDetail,
                    ClearCacheSeller,
                    ClearCacheCatalog,
                    SiteName,
                    CacheSetupBannerView,
                    CacheSetupCartView,
                    CacheSetupSellerView,
                    CacheSetupCatalogView,
                    CacheSetupProdDetailView,
                    MainPage,
                    OrderView,
                    OrderRegisterView,
                    OrderConfirmView,
                    DiscountList,
                    DiscountDetail,
                    PaymentFormView,
                    PaymentProgressView,
                    )

app_name = 'store'

urlpatterns = [
    path('catalog/', CatalogListView.as_view(), name='catalog'),
    path('catalog/<slug:slug>/', CatalogListView.as_view(), name='category'),
    path('product/<slug:slug>/', ProductDetailView.as_view(), name='product-detail'),
    path('', MainPage.as_view(), name='index'),
    path('order/<int:pk>/payment/', PaymentFormView.as_view(), name='payment-form'),
    path('order/<int:pk>/payment/progress/', PaymentProgressView.as_view(), name='payment-progress'),
    path('order-reg/', OrderRegisterView.as_view(), name='order_reg'),
    path('order-create/<int:pk>/', OrderView.as_view(), name='order_create'),
    path('order-confirm/<int:pk>/', OrderConfirmView.as_view(), name='order_confirm'),
    path('settings/', SettingsView.as_view(), name='settings'),
    path('clear-all/', ClearCacheAll.as_view(), name='clear_all_cache'),
    path('clear-banner/', ClearCacheBanner.as_view(), name='clear_banner_cache'),
    path('clear-cart/', ClearCacheCart.as_view(), name='clear_cart_cache'),
    path('clear-seller/', ClearCacheSeller.as_view(), name='clear_seller'),
    path('clear-catalog/', ClearCacheCatalog.as_view(), name='clear_catalog'),
    path('clear-product-detail/', ClearCacheProductDetail.as_view(), name='clear_product_detail'),
    path('site-name/', SiteName.as_view(), name='site_name'),
    path('cache-time-banner/', CacheSetupBannerView.as_view(), name='cache_time_banner'),
    path('cache-time-cart/', CacheSetupCartView.as_view(), name='cache_time_cart'),
    path('cache-time-prod-detail/', CacheSetupProdDetailView.as_view(), name='cache_time_prod_detail'),
    path('cache-time-seller/', CacheSetupSellerView.as_view(), name='cache_time_seller'),
    path('cache-time-catalog/', CacheSetupCatalogView.as_view(), name='cache_time_catalog'),
    path('discounts/', DiscountList.as_view(), name='discounts'),
    path('discounts/<slug:slug>/', DiscountDetail.as_view(), name='discount_details'),
]

megano/authorization/models.py
from django.contrib.auth.models import User
from django.db import models
from django.utils.translation import gettext_lazy as _

from imagekit.models import ProcessedImageField
from pilkit.processors import ResizeToFit

from services.slugify import slugify


class BaseModel(models.Model):
    """"
    Базовый класс модели
    """

    def delete(self, *arg, **kwargs):
        """"
        Функция, меняющая поведение delete на мягкое удаление
        """
        self.archived = True
        self.save()
        return self

    class Meta:
        abstract = True


def profile_images_directory_path(instance: 'Profile', filename: str) -> str:
    """
    Функция генерирует путь сохранения изображений с привязкой к id товара

    :param instance: объект ProductImage
    :param filename: имя файла
    :return: str - путь для сохранения
    """

    return f'profiles/profile_{instance.id}/{filename}'


class Profile(BaseModel):
    """
    Модель профиля всех пользователей
    """

    class Role(models.TextChoices):
        """
        Модель ролей пользователей
        """

        ADMIN = 'admin'
        STORE = 'store'
        BUYER = 'buyer'

    user = models.OneToOneField(User, verbose_name=_('Пользователь'), on_delete=models.CASCADE)
    slug = models.SlugField(_('Слаг'), max_length=150, default='', null=True, blank=True)
    phone = models.CharField(_('Teleфон'), null=True, blank=True, unique=True)
    description = models.CharField(_('Описание'), max_length=100)
    avatar = ProcessedImageField(
        blank=True,
        verbose_name=_('Фотография профиля'),
        upload_to=profile_images_directory_path,
        options={"quality": 80},
        processors=[ResizeToFit(200, 155, mat_color='white')],
        null=True
    )
    archived = models.BooleanField(default=False, verbose_name=_('Архивация'))
    name_store = models.CharField(_('Имя магазина'), max_length=50, blank=True, null=True)
    address = models.CharField(_('Адрес'), max_length=100)
    viewed_orders = models.ForeignKey(
        'store.Product',
        verbose_name=_('Связанные заказы'),
        blank=True,
        null=True,
        on_delete=models.CASCADE
    )
    role = models.CharField(_('Роль'), default=Role.BUYER, choices=Role.choices)

    def __str__(self) -> str:
        return f'{self.user}'

    def save(self, *args, **kwargs):
        if self.role == 'store' and self.name_store:
            self.slug = slugify(self.name_store)
        else:
            self.slug = slugify(self.user.username)

        super(Profile, self).save(*args, **kwargs)

    class Meta:
        db_table = 'Profiles'
        ordering = ['id', 'user']
        verbose_name = _('Профиль')
        verbose_name_plural = _('Профили')
        permissions = (
            ('store', 'has offers for sale'),
            ('user', 'all site users'),
            ('buyer', 'only buys goods'),
            ('admin', 'manages the site'),
        )


class StoreSettings(models.Model):
    """
    Модель настроек магазина
    """

    class Delivery(models.IntegerChoices):
        """
        Модель вариантов доставки
        """

        FREE = 1, _('Обычная доставка')
        EXPRESS = 2, _('Экспресс-доставка')

        __empty__ = _('Выберите доставку')

    class Payment(models.IntegerChoices):
        """
        Модель вариантов оплаты
        """

        OWN_CARD = 1, _('Онлайн картой')
        ANOTHER_CARD = 2, _('Онлайн со случайного счета')

        __empty__ = _('Выберите оплату')

    profile = models.OneToOneField(Profile, on_delete=models.CASCADE, related_name='store_settings')
    delivery_type = models.IntegerField(_('Способ доставки'), choices=Delivery.choices)
    payment = models.IntegerField(_('Способ оплаты'), choices=Payment.choices)

    def __str__(self) -> str:
        return f"{self.profile.name_store}"

    class Meta:
        db_table = 'StoreSettings'
        ordering = ['id', 'profile']
        verbose_name = _('Настройки магазина')
        verbose_name_plural = _('Настройки магазина')

megano/cart/models.py
from django.db import models
from django.urls import reverse
from django.utils.translation import gettext_lazy as _

from store.models import Product, Orders


class Cart(models.Model):
    """
    Описание модели Корзины

    Orders  - :model:`store.Orders`\n
    Product - :model:`store.Product`
    """

    ordering = _('Заказ')

    order = models.ForeignKey(Orders, on_delete=models.CASCADE, verbose_name=_('Заказ'))
    products = models.ForeignKey(Product, on_delete=models.CASCADE, verbose_name=_('Продукты'))
    quantity = models.IntegerField(default=1, verbose_name=_('Количество'))
    created_at = models.DateTimeField(auto_now_add=True, verbose_name=_('Дата создания'), db_index=True)
    updated_at = models.DateTimeField(auto_now=True, verbose_name=_('Дата изменения'))

    def __str__(self) -> str:
        """
        Возвращает имя пользователя и название продукта в виде:
        username: product_name
        """

        return f'({self.ordering} №_{self.order.id}'

    def get_absolute_url(self) -> str:
        """
        Возвращает путь на детальную страницу товаров корзины.
        """

        return reverse('detail', kwargs={'id': self.id})

    class Meta:
        db_table = 'carts'
        ordering = ['-created_at']
        verbose_name = _('корзину')
        verbose_name_plural = _('корзины')

megano/templates/authorization/about-seller.html
{% extends 'base/base.html' %}
{% load phone_tags %}
{% load i18n  static %}
{% load cache %}


{% block content %}
  <div class="Middle Middle_top">
    <div class="Middle-top">
      <div class="wrap">
        <div class="Middle-header">
          <h1 class="Middle-title">{% translate 'About ' %}{{ seller.name_store }}
          </h1>
          <ul class="breadcrumbs Middle-breadcrumbs">
            <li class="breadcrumbs-item"><a href="{% url 'store:index' %}">{% translate 'home' %}</a>
            </li>
            <li class="breadcrumbs-item breadcrumbs-item_current"><span>{% translate 'About Us' %}</span>
            </li>
          </ul>
        </div>
      </div>
    </div>
    <div class="Section Section_column Section_columnLeft Section_columnWide">
      <div class="wrap">
        <div class="Section-column">
          <div class="Section-columnSection Section-columnSection_mark">
            <div class="media media_advantage">
              <div class="media-image">
                <img src="{% static 'assets/img/icons/advantages/shipping.svg' %}" alt="shipping.svg"/>
              </div>
              <div class="media-content">
                <strong class="media-title">{% translate 'Shipping & Returns' %}</strong>
                <p class="media-text">{% translate 'World wide shipping' %}</p>
              </div>
            </div>
          </div>
          <div class="Section-columnSection Section-columnSection_mark">
            <div class="media media_advantage">
              <div class="media-image">
                <img src="{% static 'assets/img/icons/advantages/moneyBack.svg' %}" alt="moneyBack.svg"/>
              </div>
              <div class="media-content">
                <strong class="media-title">{% translate 'Money Back' %}
                </strong>
                <p class="media-text">{% translate 'Guaranted payments' %}
                </p>
              </div>
            </div>
          </div>
          <div class="Section-columnSection Section-columnSection_mark">
            <div class="media media_advantage">
              <div class="media-image">
                <img src="{% static 'assets/img/icons/advantages/support.svg' %}" alt="support.svg"/>
              </div>
              <div class="media-content">
                <strong class="media-title">{% translate 'Support Policy' %}</strong>
                <p class="media-text">{% translate 'Fast support team' %}</p>
              </div>
            </div>
          </div>
          <div class="Section-columnSection Section-columnSection_mark">
            <div class="media media_advantage">
              <div class="media-image">
                <img src="{% static 'assets/img/icons/advantages/quality.svg' %}" alt="quality.svg"/>
              </div>
              <div class="media-content">
                <strong class="media-title">{% translate 'Quality Guarantee' %}</strong>
                <p class="media-text">{% translate 'Best guaranted items' %}</p>
              </div>
            </div>
          </div>
          {% if seller.phone %}
            <div class="Section-columnSection Section-columnSection_mark">
              <div class="media media_middle">
                <div class="media-image"><img src="{% static 'assets/img/icons/contacts/phone.svg' %}" alt="phone.svg"/>
                </div>
                <div class="media-content">
                  {% translate 'Phone' %}:+7 {% change_phone_format seller.phone %}
                </div>
              </div>
            </div>
          {% endif %}
          {% if seller.address %}
            <div class="Section-columnSection Section-columnSection_mark">
              <div class="media media_middle">
                <div class="media-image">
                  <img src="{% static 'assets/img/icons/contacts/address.svg' %}" alt="address.svg"/>
                </div>
                <div class="media-content">
                  {{ seller.address }}
                </div>
              </div>
            </div>
          {% endif %}
          {% if seller.user.email %}
            <div class="Section-columnSection Section-columnSection_mark">
              <div class="media media_middle">
                <div class="media-image">
                  <img src="{% static 'assets/img/icons/contacts/mail.svg' %}" alt="mail.svg"/>
                </div>
                <div class="media-content">
                  {{ seller.user.email }}
                </div>
              </div>
            </div>
          {% endif %}
          <div class="Section-columnSection">
            <header class="Section-header">
              <strong class="Section-title">{% translate 'Follow Us' %}
              </strong>
            </header>
            <div class="Section-columnContent">
              <div class="Footer-payments Footer-payments_column">
                <div><img src="{% static 'assets/img/icons/socialContent/fb.png' %}" alt="fb.png"/>
                </div>
                <div><img src="{% static 'assets/img/icons/socialContent/tw.png' %}" alt="tw.png"/>
                </div>
                <div><img src="{% static 'assets/img/icons/socialContent/gg.png' %}" alt="gg.png"/>
                </div>
                <div><img src="{% static 'assets/img/icons/socialContent/in.png' %}" alt="in.png"/>
                </div>
                <div><img src="{% static 'assets/img/icons/socialContent/pt.png' %}" alt="pt.png"/>
                </div>
                <div><img src="{% static 'assets/img/icons/socialContent/ml.png' %}" alt="ml.png"/>
                </div>
              </div>
            </div>
          </div>
        </div>
        <div class="Section-content">
          <article class="Article">
            <div class="Article-section">
              <div class="row row_verticalCenter row_maxHalf">
                <div class="row-block">
                  <h2>{% translate 'Why Choose' %} {{ seller.name_store }}?
                  </h2>
                  {% if seller.description %}
                    <p>{{ seller.description }}</p>
                  {% else %}
                    <p>{% translate 'Продавец пока не оставил описания' %}</p>
                  {% endif %}
                  <div><a class="btn btn_primary" href="#">{% translate 'Get Started' %}</a>
                  </div>
                </div>
                <div class="row-block">
                  {% if seller.avatar %}
                    <div class="pict">
                      <img src='{{ seller.avatar.url }}'>
                    </div>
                  {% endif %}
                </div>
              </div>
            </div>
            <header class="Section-header">
              <h2 class="Section-title">{% translate 'Popular Products' %}
              </h2>
            </header>
            <div class="Cards">
              {% if top_offers %}
                {% cache 3600 top_offers seller.id %}
                  {% for offer in top_offers %}
                    <div class="Card">
                      <a class="Card-picture" href="#">
                        {% if offer.product.preview %}
                          <img src="{{ offer.product.preview.url }}"/>
                        {% else %}
                          <img src="{% static 'assets/img/content/home/placeholder.png' %}"
                               alt="empty_photo"/>
                        {% endif %}
                      </a>
                      <div class="Card-content">
                        <strong class="Card-title">
                          <a href="{% url 'store:product-detail' slug=offer.product.slug %}">
                            {{ offer.product.name }}
                          </a>
                        </strong>
                        <div class="Card-description">
                          <div class="Card-cost">
                            <span class="Card-price">${{ offer.unit_price }}</span>
                          </div>
                          <div class="Card-category">
                            {% for tag in offer.product.tags.all %}
                              {% if not forloop.last %}{{ tag }}/{% else %}{{ tag }}{% endif %}
                            {% endfor %}
                          </div>
                          <div class="Card-hover">
                            <a class="Card-btn" href="{% url 'cart:add_product_to_cart' offer.id %}">
                              <img src="{% static 'assets/img/icons/card/cart.svg' %}" alt="cart.svg"/>
                            </a>
                            <a class="Card-btn" href="">
                              <form action="{% url 'compare:add_to_comparison' offer.product.id %}"
                                    method="get">
                                <button type="submit">
                                  <img src="{% static 'assets/img/icons/card/change.svg' %}"
                                       alt="change.svg"/>
                                </button>
                              </form>
                            </a>
                          </div>
                        </div>
                      </div>
                    </div>
                  {% endfor %}
                {% endcache %}
              {% endif %}
            </div>
          </article>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

megano/templates/authorization/detailed_order_page.html
{% extends 'base/base.html' %}
{% load split_user_address %}
{% load i18n static %}


{% block content %}
  <div class="Middle Middle_top">
    <div class="Middle-top">
      <div class="wrap">
        <div class="Middle-header">
          <h1 class="Middle-title">{% translate 'Заказ' %} №{{ order.id }}
          </h1>
        </div>
      </div>
    </div>
    <div class="Section">
      <div class="wrap">
        <div class="Section-content">
          <div class="Orders">
          </div>
          <div class="Order">
            <div class="Order-infoBlock">
              <div class="Order-personal">
                <div class="row">
                  <div class="row-block">
                    <div class="Order-info Order-info_date">
                      <div class="Order-infoType">{% translate 'Дата заказа' %}:
                      </div>
                      <div class="Order-infoContent">{{ order.created_at|date:"d.m.Y" }}
                      </div>
                    </div>
                    <div class="Order-info">
                      <div class="Order-infoType">{% translate 'ФИО' %}:
                      </div>
                      <div class="Order-infoContent"> {% if user.first_name and user.last_name %}
                        {{ user.first_name }} {{ user.last_name }}
                      {% else %}
                        {% firstof user.first_name user.username %}
                      {% endif %}
                      </div>

                    </div>
                    <div class="Order-info">
                      <div class="Order-infoType">{% translate 'Телефон' %}:
                      </div>
                      <div class="Order-infoContent">+7{{ order.profile.phone }}
                      </div>
                    </div>
                    <div class="Order-info">
                      <div class="Order-infoType">{% translate 'E-mail' %}:
                      </div>
                      <div class="Order-infoContent">{{ user.email }}
                      </div>
                    </div>
                  </div>
                  <div class="row-block">
                    <div class="Order-info Order-info_delivery">
                      <div class="Order-infoType">{% translate 'Тип доставки' %}:
                      </div>
                      <div class="Order-infoContent">{{ order.get_delivery_type_display }}
                      </div>
                    </div>
                    {% with address=order.address|split_string:" " %}
                      {#                        поменять на address=order.address|#}
                      <div class="Order-info">
                        <div class="Order-infoType">{% translate 'Город' %}:
                        </div>
                        <div class="Order-infoContent">{{ address|first }}
                        </div>
                      </div>
                      <div class="Order-info">
                        <div class="Order-infoType">{% translate 'Адрес' %}:
                        </div>
                        <div class="Order-infoContent">{{ address|last }}
                        </div>
                      </div>
                    {% endwith %}
                    <div class="Order-info Order-info_pay">
                      <div class="Order-infoType">{% translate 'Оплата' %}:
                      </div>
                      <div class="Order-infoContent">{{ order.get_payment_display }}
                      </div>
                    </div>
                    <div class="Order-info Order-info_status">
                      <div class="Order-infoType">{% translate 'Статус' %}:
                      </div>
                      <div class="Order-infoContent">{{ order.get_status_display }}
                      </div>
                    </div>
                    {% if order.status_exception %}
                      <div class="Order-info Order-info_error">
                        <div class="Order-infoType">{% translate 'Оплата не прошла' %}:
                        </div>
                        <div class="Order-infoContent">{{ order.status_exception }}
                        </div>
                      </div>
                    {% endif %}
                  </div>
                </div>
              </div>
              {% for product in order.products.all %}
                <div class="Cart Cart_order">
                  <div class="Cart-product">
                    <div class="Cart-block Cart-block_row">
                      <div class="Cart-block Cart-block_pict">
                        <a class="Cart-pict" href="#">
                            {% if product.preview %}
                              <img
                                      class="Cart-img"
                                      src="{{ product.preview.url }}"
                                      alt="card.jpg"/>
                            {% else %}
                              <img
                                      class="Cart-img"
                                      src="{% static 'assets/img/content/home/placeholder.png' %}"
                                      alt="empty_photo"/>
                            {% endif %}
                          </a>
                      </div>
                      <div class="Cart-block Cart-block_info"><a class="Cart-title"
                                                                 href="{% url 'store:product-detail' product.slug %}">
                        {{ product.name }}</a>
                        <div class="Cart-desc">{{ product.description.title }}
                        </div>
                      </div>
                      <div class="Cart-block Cart-block_price">
                        <div class="Cart-price">{{ product.offers.first.unit_price }}$
                        </div>
                      </div>
                    </div>
                    <div class="Cart-block Cart-block_row">
                      <div class="Cart-block Cart-block_amount">{{ product.cart_set.first.quantity }} {% translate 'шт' %}.
                      </div>
                    </div>
                  </div>
                </div>
              {% endfor %}
              <div class="Cart-total">
                <div class="Cart-block Cart-block_total">
                  <strong class="Cart-title">{% translate 'Итого' %}:<span class="Cart-price">{{ order.total_payment }}$</span>
                  </strong>
                </div>
                {% if order.status != 1 %}
                  <div class="Cart-block">
                    <a class="btn btn_primary btn_lg" href="{% url 'store:payment-form' pk=order.id %}">{% translate 'Оплатить' %}</a>
                  </div>
                {% endif %}
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>

{% endblock %}

megano/templates/authorization/profile_detail.html
{% extends 'authorization/account.html' %}
{% load i18n static %}


{% block content123 %}
  <div class="Section-content">
    <div class="Account">
      <div class="Account-group">
        <div class="Account-column">
          {% if user.profile.avatar %}
            <div class="Account-avatar"><img src="{{ user.profile.avatar.url }}" alt="card.jpg"/>
            </div>
          {% endif %}
        </div>
        <div class="Account-column">
          <div class="Account-name">
            {% if user.first_name and user.last_name %}
              {{ user.first_name }} {{ user.last_name }}
            {% else %}
              {% firstof user.first_name user.username %}
            {% endif %}
          </div>
          <a class="Account-editLink" href="{% url 'profile:profile' slug=user.profile.slug %}">{% translate 'Редактировать профиль' %}
            </a>
        </div>
      </div>
      <div class="Account-group">
        <div class="Account-column Account-column_full">
          {% if order %}
            {% for order_id in order %}
              <div class="Order Order_anons">
                <div class="Order-personal">
                  <div class="row">
                    <div class="row-block"><a class="Order-title"
                                              href="{% url 'profile:detailed_order'
                                                  slug=request.user.profile.slug pk=order_id.pk %}">
                      {% translate 'Заказ' %}&#32;<span
                        class="Order-numberOrder">
                    №{{ order_id.id }} </span>&#32;{% translate 'от' %}&#32;
                      <span class="Order-dateOrder">{{ order_id.created_at|date:"d.m.Y" }}</span></a>
                      <div class="Account-editLink">
                        <a href="{% url 'profile:history_orders' slug=request.user.profile.slug %}">
                          {% translate 'История заказов' %}</a>
                      </div>
                    </div>

                    <div class="row-block">

                      <div class="Order-info Order-info_delivery">
                        <div class="Order-infoType">{% translate 'Тип доставки' %}:
                        </div>
                        <div class="Order-infoContent">{{ order_id.get_delivery_type_display }}
                        </div>
                      </div>
                      <div class="Order-info Order-info_pay">
                        <div class="Order-infoType">{% translate 'Оплата' %}:
                        </div>
                        <div class="Order-infoContent">{{ order_id.get_payment_display }}
                        </div>
                      </div>

                      <div class="Order-info">
                        <div class="Order-infoType">{% translate 'Общая стоимость' %}:
                        </div>
                        <div class="Order-infoContent">{{ order_id.total_payment }}$
                        </div>
                      </div>
                      <div class="Order-info Order-info_status">
                        <div class="Order-infoType">{% translate 'Статус' %}:
                        </div>
                        <div class="Order-infoContent">{{ order_id.get_status_display }}
                        </div>
                      </div>

                    </div>
                  </div>
                </div>
              </div>
            {% endfor %}
          {% else %}
            <h5>{% translate 'У вас нет заказов' %}</h5>
          {% endif %}
        </div>
      </div>
    </div>
  </div>
{% endblock %}