megano/authorization/urls.py
from django.urls import path

from .views import (
    ProfileDetailView,
    ProfileUpdateView,
    ProfileOrders,
    SellerDetail,
    RegisterView,
    UserLoginView,
    UserLogoutView,
    ProfileOrderPage,
    ProfileHistoryView,
)

app_name = 'profile'

urlpatterns = [
    path('personal_account/<slug:slug>/', ProfileDetailView.as_view(), name='profile_details'),
    path('personal_account/<slug:slug>/profile_date_form/', ProfileUpdateView.as_view(), name='profile'),
    path('personal_account/<slug:slug>/history_orders/', ProfileOrders.as_view(), name='history_orders'),
    path('personal_account/<slug:slug>/history_view/', ProfileHistoryView.as_view(), name='history_view'),
    path('seller/<slug:slug>/', SellerDetail.as_view(), name='seller'),
    path('register/', RegisterView.as_view(), name='register'),
    path('login/', UserLoginView.as_view(), name='login'),
    path('logout/', UserLogoutView.as_view(), name='logout'),
    path('personal_account/<slug:slug>/history_orders/detailed_order_page/<int:pk>/',
         ProfileOrderPage.as_view(), name='detailed_order'),
]

megano/cart/urls.py
from django.urls import path

from .views import (
    AddProductToCartView,
    AddProductView,
    TakeProductView,
    CartListView,
    DeleteProductFromCartView,
    ClearCartView
)

app_name = 'cart'

urlpatterns = [
    path('', CartListView.as_view(), name='index'),
    path('<int:offer_id>/', AddProductToCartView.as_view(), name='add_product_to_cart'),
    path('add_product/<slug:slug>/', AddProductView.as_view(), name='add_product'),
    path('take_product/<slug:slug>/', TakeProductView.as_view(), name='take_product'),
    path('delete_product/<slug:slug>/', DeleteProductFromCartView.as_view(), name='delete_product'),
    path('cart/clear/', ClearCartView.as_view(), name='cart_clear'),
]

megano/megano/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls.i18n import i18n_patterns
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('i18n/', include('django.conf.urls.i18n')),
]

urlpatterns += i18n_patterns(
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('cart/', include('cart.urls')),
    path('', include('store.urls')),
    path('', include('compare.urls')),
    path('auth/', include('authorization.urls')),
)
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

megano/store/urls.py
from django.urls import path

from .views import (CatalogListView,
                    ProductDetailView,
                    SettingsView,
                    ClearCacheAll,
                    ClearCacheBanner,
                    ClearCacheCart,
                    ClearCacheProductDetail,
                    ClearCacheSeller,
                    ClearCacheCatalog,
                    SiteName,
                    CacheSetupBannerView,
                    CacheSetupCartView,
                    CacheSetupSellerView,
                    CacheSetupCatalogView,
                    CacheSetupProdDetailView,
                    MainPage,
                    OrderView,
                    OrderRegisterView,
                    OrderConfirmView,
                    DiscountList,
                    DiscountDetail,
                    PaymentFormView,
                    PaymentProgressView,
                    )

app_name = 'store'

urlpatterns = [
    path('catalog/', CatalogListView.as_view(), name='catalog'),
    path('catalog/<slug:slug>/', CatalogListView.as_view(), name='category'),
    path('product/<slug:slug>/', ProductDetailView.as_view(), name='product-detail'),
    path('', MainPage.as_view(), name='index'),
    path('order/<int:pk>/payment/', PaymentFormView.as_view(), name='payment-form'),
    path('order/<int:pk>/payment/progress/', PaymentProgressView.as_view(), name='payment-progress'),
    path('order-reg/', OrderRegisterView.as_view(), name='order_reg'),
    path('order-create/<int:pk>/', OrderView.as_view(), name='order_create'),
    path('order-confirm/<int:pk>/', OrderConfirmView.as_view(), name='order_confirm'),
    path('settings/', SettingsView.as_view(), name='settings'),
    path('clear-all/', ClearCacheAll.as_view(), name='clear_all_cache'),
    path('clear-banner/', ClearCacheBanner.as_view(), name='clear_banner_cache'),
    path('clear-cart/', ClearCacheCart.as_view(), name='clear_cart_cache'),
    path('clear-seller/', ClearCacheSeller.as_view(), name='clear_seller'),
    path('clear-catalog/', ClearCacheCatalog.as_view(), name='clear_catalog'),
    path('clear-product-detail/', ClearCacheProductDetail.as_view(), name='clear_product_detail'),
    path('site-name/', SiteName.as_view(), name='site_name'),
    path('cache-time-banner/', CacheSetupBannerView.as_view(), name='cache_time_banner'),
    path('cache-time-cart/', CacheSetupCartView.as_view(), name='cache_time_cart'),
    path('cache-time-prod-detail/', CacheSetupProdDetailView.as_view(), name='cache_time_prod_detail'),
    path('cache-time-seller/', CacheSetupSellerView.as_view(), name='cache_time_seller'),
    path('cache-time-catalog/', CacheSetupCatalogView.as_view(), name='cache_time_catalog'),
    path('discounts/', DiscountList.as_view(), name='discounts'),
    path('discounts/<slug:slug>/', DiscountDetail.as_view(), name='discount_details'),
]

megano/authorization/models.py
from django.contrib.auth.models import User
from django.db import models
from django.utils.translation import gettext_lazy as _

from imagekit.models import ProcessedImageField
from pilkit.processors import ResizeToFit

from services.slugify import slugify


class BaseModel(models.Model):
    """"
    Базовый класс модели
    """

    def delete(self, *arg, **kwargs):
        """"
        Функция, меняющая поведение delete на мягкое удаление
        """
        self.archived = True
        self.save()
        return self

    class Meta:
        abstract = True


def profile_images_directory_path(instance: 'Profile', filename: str) -> str:
    """
    Функция генерирует путь сохранения изображений с привязкой к id товара

    :param instance: объект ProductImage
    :param filename: имя файла
    :return: str - путь для сохранения
    """

    return f'profiles/profile_{instance.id}/{filename}'


class Profile(BaseModel):
    """
    Модель профиля всех пользователей
    """

    class Role(models.TextChoices):
        """
        Модель ролей пользователей
        """

        ADMIN = 'admin'
        STORE = 'store'
        BUYER = 'buyer'

    user = models.OneToOneField(User, verbose_name=_('Пользователь'), on_delete=models.CASCADE)
    slug = models.SlugField(_('Слаг'), max_length=150, default='', null=True, blank=True)
    phone = models.CharField(_('Teleфон'), null=True, blank=True, unique=True)
    description = models.CharField(_('Описание'), max_length=100)
    avatar = ProcessedImageField(
        blank=True,
        verbose_name=_('Фотография профиля'),
        upload_to=profile_images_directory_path,
        options={"quality": 80},
        processors=[ResizeToFit(200, 155, mat_color='white')],
        null=True
    )
    archived = models.BooleanField(default=False, verbose_name=_('Архивация'))
    name_store = models.CharField(_('Имя магазина'), max_length=50, blank=True, null=True)
    address = models.CharField(_('Адрес'), max_length=100)
    viewed_orders = models.ForeignKey(
        'store.Product',
        verbose_name=_('Связанные заказы'),
        blank=True,
        null=True,
        on_delete=models.CASCADE
    )
    role = models.CharField(_('Роль'), default=Role.BUYER, choices=Role.choices)

    def __str__(self) -> str:
        return f'{self.user}'

    def save(self, *args, **kwargs):
        if self.role == 'store' and self.name_store:
            self.slug = slugify(self.name_store)
        else:
            self.slug = slugify(self.user.username)

        super(Profile, self).save(*args, **kwargs)

    class Meta:
        db_table = 'Profiles'
        ordering = ['id', 'user']
        verbose_name = _('Профиль')
        verbose_name_plural = _('Профили')
        permissions = (
            ('store', 'has offers for sale'),
            ('user', 'all site users'),
            ('buyer', 'only buys goods'),
            ('admin', 'manages the site'),
        )


class StoreSettings(models.Model):
    """
    Модель настроек магазина
    """

    class Delivery(models.IntegerChoices):
        """
        Модель вариантов доставки
        """

        FREE = 1, _('Обычная доставка')
        EXPRESS = 2, _('Экспресс-доставка')

        __empty__ = _('Выберите доставку')

    class Payment(models.IntegerChoices):
        """
        Модель вариантов оплаты
        """

        OWN_CARD = 1, _('Онлайн картой')
        ANOTHER_CARD = 2, _('Онлайн со случайного счета')

        __empty__ = _('Выберите оплату')

    profile = models.OneToOneField(Profile, on_delete=models.CASCADE, related_name='store_settings')
    delivery_type = models.IntegerField(_('Способ доставки'), choices=Delivery.choices)
    payment = models.IntegerField(_('Способ оплаты'), choices=Payment.choices)

    def __str__(self) -> str:
        return f"{self.profile.name_store}"

    class Meta:
        db_table = 'StoreSettings'
        ordering = ['id', 'profile']
        verbose_name = _('Настройки магазина')
        verbose_name_plural = _('Настройки магазина')

megano/cart/models.py
from django.db import models
from django.urls import reverse
from django.utils.translation import gettext_lazy as _

from store.models import Product, Orders


class Cart(models.Model):
    """
    Описание модели Корзины

    Orders  - :model:`store.Orders`\n
    Product - :model:`store.Product`
    """

    ordering = _('Заказ')

    order = models.ForeignKey(Orders, on_delete=models.CASCADE, verbose_name=_('Заказ'))
    products = models.ForeignKey(Product, on_delete=models.CASCADE, verbose_name=_('Продукты'))
    quantity = models.IntegerField(default=1, verbose_name=_('Количество'))
    created_at = models.DateTimeField(auto_now_add=True, verbose_name=_('Дата создания'), db_index=True)
    updated_at = models.DateTimeField(auto_now=True, verbose_name=_('Дата изменения'))

    def __str__(self) -> str:
        """
        Возвращает имя пользователя и название продукта в виде:
        username: product_name
        """

        return f'({self.ordering} №_{self.order.id}'

    def get_absolute_url(self) -> str:
        """
        Возвращает путь на детальную страницу товаров корзины.
        """

        return reverse('detail', kwargs={'id': self.id})

    class Meta:
        db_table = 'carts'
        ordering = ['-created_at']
        verbose_name = _('корзину')
        verbose_name_plural = _('корзины')

megano/store/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django.utils.translation import gettext_lazy as _
from multiupload.fields import MultiFileField

from authorization.models import Profile
from .models import Orders, Product


class ReviewsForm(forms.Form):
    review = forms.CharField(widget=forms.Textarea, max_length=100)


class OrderCreateForm(forms.ModelForm):
    """
    Класс формы для оформления Заказа.
    """

    name_placeholder = _("Иванов Иван Иванович")

    name = forms.CharField(
        max_length=100,
        label='ФИО',
        widget=forms.TextInput(attrs={
            'class': "form-input",
            'id': "name",
            'name': "name",
            'type': "text",
            'placeholder': name_placeholder,
        }),
    )
    phone = forms.CharField(
        max_length=20,
        label='Телефон',
        widget=forms.TextInput(attrs={
            'class': "form-input",
            'id': "phone",
            'name': "phone",
            'type': "text",
            'placeholder': "+79991230000",
            'data-mask': "+7(999)9999999",
        }),
    )
    delivery = forms.ChoiceField(
        choices=Orders.Delivery.choices[1:],
        widget=forms.RadioSelect(attrs={
            'class': "toggle-box",
            'id': "delivery",
            'name': "delivery",
            'type': "radio",
            'checked': "checked"
        }),
    )
    payment = forms.ChoiceField(
        choices=Orders.Payment.choices[1:],
        widget=forms.RadioSelect(attrs={
            'class': "toggle-box",
            'id': "payment",
            'name': "payment",
            'type': "radio",
        }),
    )
    city = forms.CharField(max_length=100, label='Город', help_text=_('Город проживания'))
    address = forms.CharField(max_length=200, label='Адрес', help_text=_('Адрес доставки'))
    email = forms.EmailField(max_length=80, label='Почта', help_text=_('Почта'))

    def clean_phone(self):
        """"
        Функция для очистки номера проверки его на уникальность и приведения к int
        """
        phone_str = self.cleaned_data['phone']
        chars_to_remove = ['(', ')']
        for char in chars_to_remove:
            phone_str = phone_str.replace(char, '')
        phone = phone_str[2:]
        return phone

    class Meta:
        model = Profile
        fields = [
            'name', 'phone', 'city', 'address',
            'delivery', 'payment',
        ]


class RegisterForm(UserCreationForm):
    """
    Класс формы для регистрации пользователя
    """

    username = forms.CharField(label='Логин', widget=forms.TextInput(attrs={'class': 'form-input'}))
    password1 = forms.CharField(label='Пароль', widget=forms.PasswordInput(attrs={'class': 'form-input'}))
    password2 = forms.CharField(label='Повтор пароля', widget=forms.PasswordInput(attrs={'class': 'form-input'}))
    phone = forms.CharField(
        max_length=20,
        label='Телефон',
        widget=forms.TextInput(attrs={
            'class': "form-input",
            'id': "phone",
            'name': "phone",
            'type': "text",
            'placeholder': "+79991230000",
        }),
    )

    def clean_phone(self):
        phone = self.cleaned_data['phone']
        if Profile.objects.filter(phone=phone).exists():
            raise forms.ValidationError(_("Такой телефон уже существует"))

    def clean_username(self):
        username = self.cleaned_data['username']
        if User.objects.filter(username=username).exists():
            raise forms.ValidationError(_("Такой логин уже существует"))

        return username

    def clean_email(self):
        email = self.cleaned_data['email']
        if User.objects.filter(email=email).exists():
            raise forms.ValidationError(_("Данный email уже существует."))

    def clean_password2(self):
        passw1 = self.cleaned_data['password1']
        passw2 = self.cleaned_data['password2']
        if passw1 != passw2:
            raise forms.ValidationError(_("Пароли не совпадают"))
        if len(passw1) < 6:
            raise forms.ValidationError(_("Пароль должен содержать не менее 6 символов"))

    class Meta:
        model = User
        fields = ('username', 'phone', 'email', 'password1', 'password2')


class SearchForm(forms.ModelForm):
    name = forms.CharField(
        max_length=120,
        widget=forms.TextInput(attrs={
            'class': 'search-input',
            'id': 'query',
            'name': 'query',
            'placeholder': 'NVIDIA GeForce RTX 3060',
        })
    )

    class Meta:
        model = Product
        fields = ['name',]


class PaymentForm(forms.Form):
    bill = forms.CharField(
        widget=forms.TextInput(attrs={
            'class': 'form-input Payment-bill',
            'id': 'numero1',
            'name': 'numero1',
            'type': 'text',
            'placeholder': '9999 9999',
            'data-mask': "9999 9999",
            'data-validate': "require pay",
        })
    )


class JSONImportForm(forms.Form):
    """
    Вьюшка импорта JSON файлов
    """

    json_file = MultiFileField(label=_('json_file'), min_num=1, max_num=10)
    email = forms.EmailField(label=_('email'))

megano/templates/store/order/order.html
{% extends "base/base.html" %}
{% load i18n static %}


{% block content %}
  <div class="Middle Middle_top">
    <div class="Section Section_column Section_columnRight Section_columnWide Order">
      <div class="wrap">
        <div class="Section-column">
          <div class="Section-columnSection">
            <header class="Section-header">
              <strong class="Section-title">{% translate 'Прогресс заполнения' %}
              </strong>
            </header>
            <div class="Section-columnContent">
              <div class="NavigateProfile">
                <ul class="menu menu_vt">
                  <li class="menu-item_ACTIVE menu-item">
                    <a class="menu-link" href="#step1">{% translate 'Шаг 1. Параметры пользователя' %}</a>
                  </li>
                  <li class="menu-item"><a class="menu-link" href="#step2">{% translate 'Шаг 2. Способ доставки' %}</a>
                  </li>
                  <li class="menu-item"><a class="menu-link" href="#step3">{% translate 'Шаг 3. Способ оплаты' %}</a>
                  </li>
                  <li class="menu-item"><a class="menu-link"
                                           href="#step4">{% translate 'Шаг 4. Подтверждение заказа' %}</a>
                  </li>
                </ul>
              </div>
            </div>
          </div>
        </div>
        <div class="Section-content">
          {% if user.is_authenticated %}
            {% block order_create %}

            {% endblock %}

            {% block order_confirm %}
            {% endblock %}
          {% endif %}

          {% block order_register %}
          {% endblock %}
        </div>
      </div>
    </div>
  </div>
{% endblock %}

megano/templates/store/order/order_confirm.html
{% extends "store/order/order.html" %}
{% load i18n static %}
{% load split_user_address %}


{% block order_confirm %}
  {% if order %}
    <form action="" method="post">
      <div class="Middle Middle_top">
        <div class="Middle-top">
          <div class="wrap">
            <div class="Middle-header">
              <h1 class="Middle-title">{% translate 'Заказ' %} №{{ order.id }}
              </h1>
            </div>
          </div>
        </div>
        <div class="Section">
          <div class="wrap">
            <div class="Section-content">
              <div class="Orders">
              </div>
              <div class="Order">
                <div class="Order-infoBlock">
                  <div class="Order-personal">
                    <div class="row">
                      <div class="row-block">
                        <div class="Order-info Order-info_date">
                          <div class="Order-infoType">{% translate 'Дата заказа' %}:
                          </div>
                          <div class="Order-infoContent">
                            {{ order.created_at|date:"Y-M-d" }}
                            {{ order.created_at|time:"H:i" }}
                          </div>
                        </div>
                        <div class="Order-info">
                          <div class="Order-infoType">{% translate 'ФИО' %}:
                          </div>
                          <div class="Order-infoContent">
                            {{ user.last_name }}
                            {{ user.first_name }}
                          </div>
                        </div>
                        <div class="Order-info">
                          <div class="Order-infoType">{% translate 'Телефон' %}:
                          </div>
                          <div class="Order-infoContent">{{ order.profile.phone }}
                          </div>
                        </div>
                        <div class="Order-info">
                          <div class="Order-infoType">E-mail:
                          </div>
                          <div class="Order-infoContent">
                            {{ user.email }}
                          </div>
                        </div>
                      </div>
                      <div class="row-block">
                        <div class="Order-info Order-info_delivery">
                          <div class="Order-infoType">{% translate 'Тип доставки' %}:
                          </div>
                          <div class="Order-infoContent">{{ order.get_delivery_type_display }}
                          </div>
                        </div>
                        {% with address=order.profile.address|split_string:" " %}
                          <div class="Order-info">
                            <div class="Order-infoType">{% translate 'Город' %}:
                            </div>
                            <div class="Order-infoContent">{{ address|first }}
                            </div>
                          </div>
                          <div class="Order-info">
                            <div class="Order-infoType">{% translate 'Адрес' %}:
                            </div>
                            <div class="Order-infoContent">{{ address|last }}
                            </div>
                          </div>
                        {% endwith %}
                        <div class="Order-info Order-info_pay">
                          <div class="Order-infoType">{% translate 'Оплата' %}:
                          </div>
                          <div class="Order-infoContent">{{ order.get_payment_display }}
                          </div>

                        </div>
                        <div class="Order-info Order-info_status">
                          <div class="Order-infoType">{% translate 'Статус' %}:
                          </div>
                          <div class="Order-infoContent">{{ order.get_status_display }}
                          </div>
                        </div>
                        <div class="Order-info Order-info_error">
                          <div class="Order-infoType">{% translate 'Оплата не прошла' %}:
                          </div>
                          <div class="Order-infoContent">{% translate 'Оплата не выполнена' %}
                          </div>
                        </div>
                      </div>
                    </div>
                  </div>
                  <div class="Cart Cart_order">
                    {% for product in order.products.all %}
                      <div class="Cart-product">
                        <div class="Cart-block Cart-block_row">
                          <div class="Cart-block Cart-block_pict">
                            <a class="Card-pict" href="#">
                              {% if product.preview %}
                                <img
                                    class="Cart-img"
                                    src="{{ product.preview.url }}"
                                    alt="card.jpg"/>
                              {% else %}
                                <img
                                    class="Cart-img"
                                    src="{% static 'assets/img/content/home/placeholder.png' %}"
                                    alt="empty_photo"/>
                              {% endif %}
                            </a>
                          </div>
                          <div class="Cart-block Cart-block_info">
                            <a class="Cart-title"
                               href="{% url 'store:product-detail' product.slug %}">
                              {{ product.name }}
                            </a>
                            <div class="Cart-desc">{{ product.description.card_text }}
                            </div>
                          </div>
                          <div class="Cart-block Cart-block_price">
                            <div class="Cart-price">{{ product.offers.first.unit_price }}$
                            </div>
                          </div>
                        </div>
                        <div class="Cart-block Cart-block_row">
                          <div class="Cart-block Cart-block_amount">
                            {{ product.cart_set.first.quantity }} {% translate 'шт' %}.
                          </div>
                        </div>
                      </div>
                    {% endfor %}
                    <div class="Cart-total">
                      <div class="Cart-block Cart-block_total">
                        <strong class="Cart-title">{% translate 'Итого' %}:
                          <span class="Cart-price">{{ order.total_payment }}$</span>
                        </strong>
                      </div>
                      <div class="Cart-block">
                        <a class="btn btn_primary btn_lg"
                           href="{% url 'store:payment-form' pk=order.id %}">{% translate 'Оплатить' %}</a>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </form>
  {% else %}
    <h1>{% translate 'Заказов пока нет' %}!</h1>
  {% endif %}
{% endblock %}
order.get_delivery_type_display

megano/templates/store/order/order_register.html
{% extends "store/order/order.html" %}
{% load i18n static %}


{% block order_register %}
  <header class="Section-header Section-header_sm">
    <h2 class="Section-title">{% translate 'Шаг 1. Параметры пользователя' %}
    </h2>
  </header>
  <form class="form" method="post" action="#">
    {% csrf_token %}
    <div class="row">
      <div class="row-block">
        <div class="form-group">
          {{ form.username.label }}
          {{ form.username }}
          <div class="form-error">{{ form.username.errors }}</div>
        </div>
        <div class="form-group">
          {{ form.phone.label }}
          {{ form.phone }}
          <div class="form-error">{{ form.phone.errors }}</div>
        </div>
        <div class="form-group">
          {{ form.email.label }}
          {{ form.email }}
          <div class="form-error">{{ form.email.errors }}</div>
        </div>
      </div>
      <div class="row-block">
        <div class="form-group">
          {{ form.password1.label }}
          {{ form.password1 }}
        </div>
        <div class="form-group">
          {{ form.password2.label }}
          {{ form.password2 }}
          <div class="form-error">{{ form.password2.errors }}</div>
        </div>
        <div class="form-group">
          <a class="btn btn_muted Order-btnReg" href="{% url 'profile:login' %}">{% translate 'Я уже зарегистрирован' %}</a>
        </div>
      </div>
    </div>
    <button class="btn btn_success" type="submit">{% translate 'Дальше' %}</button>
  </form>
{% endblock %}

megano/templates/store/order/payment.html
{% extends 'base/base.html' %}
{% load i18n static %}


{% block content %}
  <div class="Middle Middle_top">
    <div class="Middle-top">
      <div class="wrap">
        <div class="Middle-header">
          <h1 class="Middle-title">{% translate 'Оплата' %}
          </h1>
          <ul class="breadcrumbs Middle-breadcrumbs">
            <li class="breadcrumbs-item"><a href="{% url 'store:index' %}">home</a>
            </li>
            <li class="breadcrumbs-item breadcrumbs-item_current"><span>{% translate 'Оплата' %}</span>
            </li>
          </ul>
        </div>
      </div>
    </div>
    <div class="Section">
      <div class="wrap">
        {% if error %}
          <h2>{{ error }}</h2>
        {% else %}
          {% if order_paid %}
            <div class="Payment-card">
              <div class="form-group">
                <h2>{% translate 'Заказ' %} №{{ request.resolver_match.kwargs.pk }} {% translate 'уже оплачен' %}</h2>
              </div>
            </div>
          {% else %}
            <form class="form Payment" action="" method="post">
              {% csrf_token %}
              <div class="Payment-card">
                <div class="form-group">
                  {% if payment_type == 1 %}
                    <label class="form-label">{% translate 'Номер карты' %} </label>
                  {% elif payment_type == 2 %}
                    <label class="form-label">{% translate 'Номер счета' %}</label>
                  {% endif %}
                  {{ form.bill }}
                </div>
                {% if payment_type == 2 %}
                  <div class="form-group">
                    <a class="btn btn_success Payment-generate" href="#">{% translate 'Сгенерировать случайный счет' %}</a>
                  </div>
                {% endif %}
              </div>
              <div class="Payment-pay">
                <button class="btn btn_primary">{% translate 'Оплатить' %}</button>
              </div>
            </form>
          {% endif %}
        {% endif %}
      </div>
    </div>
  </div>
{% endblock %}

megano/templates/store/order/payment_progress.html
{% extends 'base/base.html' %}
{% load i18n static %}


{% block content %}
  <div class="Middle Middle_top">
    <div class="Middle-top">
      <div class="wrap">
        <div class="Middle-header">
          <h1 class="Middle-title">{% translate 'Ожидание оплаты' %}
          </h1>
          <ul class="breadcrumbs Middle-breadcrumbs">
            <li class="breadcrumbs-item"><a href="{% url 'store:index' %}">home</a>
            </li>
            <li class="breadcrumbs-item breadcrumbs-item_current"><span>{% translate 'Ожидание оплаты' %}</span>
            </li>
          </ul>
        </div>
      </div>
    </div>
    <div class="Section">
      <div class="wrap">
        <div class="ProgressPayment">
          <div class="ProgressPayment-title">{% translate 'Ждем подтверждения оплаты платежной системой' %}
          </div>
          <div class="ProgressPayment-icon">
            <div class="cssload-thecube">
              <div class="cssload-cube cssload-c1"></div>
              <div class="cssload-cube cssload-c2"></div>
              <div class="cssload-cube cssload-c4"></div>
              <div class="cssload-cube cssload-c3"></div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
  <script>
    setTimeout(function () {
      window.location.href = '{% url "store:payment-progress" pk=request.resolver_match.captured_kwargs.pk %}';
    }, 5000);
  </script>
{% endblock %}